repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.24.0
    hooks:
      - id: eslint
        files: \.(js|ts)$
        types: [file]
        additional_dependencies:
          - eslint@8.57.0
          - typescript@5.8.3
          - '@typescript-eslint/eslint-plugin@6.21.0'
          - '@typescript-eslint/parser@6.21.0'
          - 'eslint-config-prettier@9.1.0'
          - 'eslint-plugin-prettier@5.1.3'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|ts|json|md|yaml|yml)$
        types: [file]
        additional_dependencies:
          - prettier@3.2.5

  - repo: local
    hooks:
      - id: typescript-check
        name: typescript-check
        entry: npx tsc --noEmit
        language: node
        pass_filenames: false
